apiVersion: v1
kind: Service
metadata:
  labels:
    appName: spark-app
  name: spark-master-svc
spec:
  ports:
    - port: 7077
      protocol: TCP
      targetPort: 7077
  selector:
    appName: spark-master
  sessionAffinity: None
  type: ClusterIP

