apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  generation: 1
  labels:
    appName: spark-worker
  name: spark-worker
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      appName: spark-worker
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        appName: spark-worker
    spec:
      containers:
        - env:
            - name: SPARK_MODE
              value: worker
            - name: SPARK_MASTER_URL
              value: spark-master-svc:7077
          image: shum979/recon-spark:0.1.0
          imagePullPolicy: IfNotPresent
          name: spark-worker
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30